theme: jekyll-theme-cayman
title: "PIBIC 2020-2021 (IHLM/UNILAB)"
description: "Material, dados, gráficos e demais resultados dos projetos PIBIC 2020-2021 (Proppg 01/2020 -PIBIC/FAPESB e PROPPG 04/2020 - PIBIC/UNILAB), sob orientação do Prof. Eric Brasil no Instituto de Humanidades e Letras do campus dos Malês, da Universidade da Integração Internacional da Lusofonia Afro-brasileira (IHLM/UNILAB)."
